//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DimProductCategory
    {
        public int ProductCategoryKey { get; set; }

        [DisplayName("Product Key")]
        public Nullable<int> ProductCategoryAlternateKey { get; set; }

        [DisplayName("Product Category")]
        public string EnglishProductCategoryName { get; set; }

        [DisplayName("Category Name")]
        public string SpanishProductCategoryName { get; set; }

        [DisplayName("French Name")]
        public string FrenchProductCategoryName { get; set; }
    }
}
