//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_Oders
    {

        [DisplayName("Id")]
        public int Id { get; set; }

        [DisplayName("Product Id")]
        public Nullable<int> PId { get; set; }

        [DisplayName("Order Name")]
        public string ordername { get; set; }

        [DisplayName("Status")]
        public string Active { get; set; }
    }
}
