//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Oders
    {
        public int Id { get; set; }
        public Nullable<int> PId { get; set; }
        public string ordername { get; set; }
        public string Active { get; set; }
    }
}
